name: "Execute in paths"
description: "Execute a command in multiple paths"

inputs:
  paths:
    description: "Paths to execute the command in"
    required: true
  run:
    description: "Script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Save \"run\" input as a bash script"
      id: save-run-script
      shell: bash
      run: |
        script_name="run-$RANDOM.sh"
        echo "#!/bin/bash" > /tmp/scripts/$script_name
        echo "${{ inputs.run }}" >> /tmp/scripts/$script_name
        chmod +x /tmp/scripts/$script_name
        echo "SCRIPT_PATH=/tmp/scripts/$script_name" >> $GITHUB_OUTPUT

    - name: "Execute script in each path"
      shell: bash
      run: |
        initial_path="$(pwd)"
        paths=$(echo "${{ inputs.paths }}" | tr '\n' ' ')
        for path in $paths; do
            echo "$path:${{ inputs.command }}"
            cd "$initial_path/$path"
            ./${{ steps.save-run-script.outputs.SCRIPT_PATH }}
            cd "$initial_path"
            echo "----------------"
        done
