ARG CRDETECTOR_IMAGE
ARG XSET_IMAGE

FROM ${CRDETECTOR_IMAGE} AS crdetector
FROM ${XSET_IMAGE} AS xset

FROM --platform=$BUILDPLATFORM node:16-bullseye-slim

COPY --from=crdetector /fakeroot /
COPY --from=xset /fakeroot /
COPY xdpyprobe /usr/bin/xdpyprobe
COPY install-chromium.sh /install-chromium.sh
COPY entrypoint.sh /entrypoint.sh

RUN /install-chromium.sh

ENV KAYAK_DOCKER=true

ENTRYPOINT ["/entrypoint.sh"]
