name: "Setup Docker"
description: "Setup QEMU and Docker Buildx"

inputs:
  platforms:
    description: "List of platforms"
    required: true

runs:
  using: composite
  steps:
    - name: "Setup QEMU"
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ inputs.platforms }}

    - name: "Setup Docker Buildx"
      uses: docker/setup-buildx-action@v2
      with:
          driver-opts: network=host
