name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platforms: [linux/amd64, linux/arm64/v8]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build "kayak/anvil:latest"
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platforms }}
          tags: ${{ inputs.tag }}
          file: ./docker/anvil/Dockerfile
          context: ./docker/anvil

      - name: Build "kayak/upx:latest"
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platforms }}
          tags: ${{ inputs.tag }}
          file: ./docker/upx/Dockerfile
          context: ./docker/upx

      - name: Build "kayak/crdetector:latest"
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platforms }}
          tags: ${{ inputs.tag }}
          file: ./docker/crdetector/Dockerfile
          context: ./docker/crdetector

      - name: Build "kayak/xset:latest"
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platforms }}
          tags: ${{ inputs.tag }}
          file: ./docker/xset/Dockerfile
          context: ./docker/xset
