name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      fail-fast: true
      matrix:
        platforms: [linux/amd64, linux/arm64/v8]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build "kayak/upx:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/upx:latest
          file: ./docker/upx/Dockerfile
          context: ./docker/upx

      - name: Build "kayak/crdetector:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/crdetector:latest
          file: ./docker/crdetector/Dockerfile
          context: ./docker/crdetector
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest

      - name: Build "kayak/xset:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/xset:latest
          file: ./docker/xset/Dockerfile
          context: ./docker/xset
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest
