name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-anvil:
    uses: xyz27900/kayak/.github/workflows/build/build.docker.yaml@main
    with:
      file: ./docker/anvil/Dockerfile
      tag: kayak/anvil:latest
    permissions:
      contents: read
