name: "Build Docker images"

env:
  NODE_VERSION: 18
  PNPM_VERSION: 8
  FONTCONFIG_VERSION: 2.14.0
  GNUTLS_VERSION: 3.7.1
  LIBFONTENC_VERSION: 1.1.4
  LIBTASN1_VERSION: 4.17.0
  LIBXFONT2_VERSION: 2.0.4
  LIBXRANDR_VERSION: 1.5.3
  LIBXSHMFENCE_VERSION: 1.3
  NOVNC_VERSION: 1.3.0
  OPENBOX_VERSION: 3.6.1
  PANGO_VERSION: 1.49.3
  TIGERVNC_VERSION: 1.12.0
  XKB_VERSION: 2.32
  XKBCOMP_VERSION: 1.4.5
  XSERVER_VERSION: 1.20.13
  USER_ID: 1000
  GROUP_ID: 1000
  USER_NAME: kayak
  GROUP_NAME: kayak

on:
  workflow_call:

jobs:
  build-docker:
    name: "Build Docker images"
    runs-on: ubuntu-latest

    env:
      PLATFORMS: linux/amd64,linux/arm64/v8
#      PLATFORMS: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Docker"
        uses: ./.github/actions/setup-docker
        with:
          platforms: arm,arm64,ppc64le,mips64,s390x

      - name: "Build kayak/upx:latest"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: localhost:5000/kayak/upx:latest
          file: ./docker/upx/Dockerfile
          context: ./docker/upx
          cache-from: type=gha,mode=max,scope=kayak/upx
          cache-to: type=gha,mode=max,scope=kayak/upx

      - name: "Build kayak/fontconfig:latest"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: localhost:5000/kayak/fontconfig:latest
          file: ./docker/fontconfig/Dockerfile
          context: ./docker/fontconfig
          build-args: |
            FONTCONFIG_VERSION=${{ env.FONTCONFIG_VERSION }}
          cache-from: type=gha,mode=max,scope=kayak/fontconfig
          cache-to: type=gha,mode=max,scope=kayak/fontconfig

      - name: "Build kayak/crdetector:latest"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: localhost:5000/kayak/crdetector:latest
          file: ./docker/crdetector/Dockerfile
          context: ./docker/crdetector
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest
          cache-from: type=gha,mode=max,scope=kayak/crdetector
          cache-to: type=gha,mode=max,scope=kayak/crdetector

      - name: "Build kayak/novnc:latest"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: localhost:5000/kayak/novnc:latest
          file: ./docker/novnc/Dockerfile
          context: ./docker/novnc
          build-args: |
            NOVNC_VERSION=${{ env.NOVNC_VERSION }}
          cache-from: type=gha,mode=max,scope=kayak/novnc
          cache-to: type=gha,mode=max,scope=kayak/novnc

      - name: "Build kayak/openbox:latest"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: localhost:5000/kayak/openbox:latest
          file: ./docker/openbox/Dockerfile
          context: ./docker/openbox
          build-args: |
            FONTCONFIG_IMAGE=localhost:5000/kayak/fontconfig:latest
            UPX_IMAGE=localhost:5000/kayak/upx:latest
            LIBXRANDR_VERSION=${{ env.LIBXRANDR_VERSION }}
            OPENBOX_VERSION=${{ env.OPENBOX_VERSION }}
            PANGO_VERSION=${{ env.PANGO_VERSION }}
          cache-from: type=gha,mode=max,scope=kayak/openbox
          cache-to: type=gha,mode=max,scope=kayak/openbox

      - name: "Build kayak/tigervnc:latest"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: localhost:5000/kayak/tigervnc:latest
          file: ./docker/tigervnc/Dockerfile
          context: ./docker/tigervnc
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest
            GNUTLS_VERSION=${{ env.GNUTLS_VERSION }}
            LIBFONTENC_VERSION=${{ env.LIBFONTENC_VERSION }}
            LIBTASN1_VERSION=${{ env.LIBTASN1_VERSION }}
            LIBXFONT2_VERSION=${{ env.LIBXFONT2_VERSION }}
            LIBXSHMFENCE_VERSION=${{ env.LIBXSHMFENCE_VERSION }}
            TIGERVNC_VERSION=${{ env.TIGERVNC_VERSION }}
            XKB_VERSION=${{ env.XKB_VERSION }}
            XKBCOMP_VERSION=${{ env.XKBCOMP_VERSION }}
            XSERVER_VERSION=${{ env.XSERVER_VERSION }}
          cache-from: type=gha,mode=max,scope=kayak/tigervnc
          cache-to: type=gha,mode=max,scope=kayak/tigervnc

      - name: "Build kayak/anvil:latest"
        uses: docker/build-push-action@v4
        with:
          load: true
          platforms: ${{ env.PLATFORMS }}
          tags: kayak/anvil:latest
          file: ./docker/anvil/Dockerfile
          context: ./docker/anvil
          cache-from: type=gha,mode=max,scope=kayak/anvil
          cache-to: type=gha,mode=max,scope=kayak/anvil

      - name: "Build kayak/chromium:cypress"
        uses: docker/build-push-action@v4
        with:
          load: true
          platforms: ${{ env.PLATFORMS }}
          tags: kayak/chromium:cypress
          file: ./docker/chromium/Dockerfile.cypress
          context: ./docker/chromium
          build-args: |
            CRDETECTOR_IMAGE=localhost:5000/kayak/crdetector:latest
          cache-from: type=gha,mode=max,scope=kayak/chromium:cypress
          cache-to: type=gha,mode=max,scope=kayak/chromium:cypress

      - name: "Build kayak/chromium:playwright"
        uses: docker/build-push-action@v4
        with:
          load: true
          platforms: ${{ env.PLATFORMS }}
          tags: kayak/chromium:playwright
          file: ./docker/chromium/Dockerfile.playwright
          context: ./docker/chromium
          build-args: |
            CRDETECTOR_IMAGE=localhost:5000/kayak/crdetector:latest
          cache-from: type=gha,mode=max,scope=kayak/chromium:playwright
          cache-to: type=gha,mode=max,scope=kayak/chromium:playwright

      - name: "Build kayak/display:latest"
        uses: docker/build-push-action@v4
        with:
          load: true
          platforms: ${{ env.PLATFORMS }}
          tags: kayak/display:latest
          file: ./docker/display/Dockerfile
          context: ./docker/display
          build-args: |
            FONTCONFIG_IMAGE=localhost:5000/kayak/fontconfig:latest
            NOVNC_IMAGE=localhost:5000/kayak/novnc:latest
            OPENBOX_IMAGE=localhost:5000/kayak/openbox:latest
            TIGERVNC_IMAGE=localhost:5000/kayak/tigervnc:latest
            USER_ID=${{ env.USER_ID }}
            GROUP_ID=${{ env.GROUP_ID }}
            USER_NAME=${{ env.USER_NAME }}
            GROUP_NAME=${{ env.GROUP_NAME }}
          cache-from: type=gha,mode=max,scope=kayak/display
          cache-to: type=gha,mode=max,scope=kayak/display

      - name: "Build kayak/ffmpeg:latest"
        uses: docker/build-push-action@v4
        with:
          load: true
          platforms: ${{ env.PLATFORMS }}
          tags: kayak/ffmpeg:latest
          file: ./docker/ffmpeg/Dockerfile
          context: ./docker/ffmpeg
          cache-from: type=gha,mode=max,scope=kayak/ffmpeg
          cache-to: type=gha,mode=max,scope=kayak/ffmpeg

      - name: "Save Docker images"
        run: |
          mkdir -p /tmp/docker-images
          docker save kayak/anvil:latest | gzip > /tmp/docker-images/kayak-anvil.tar.gz
          docker save kayak/chromium:cypress | gzip > /tmp/docker-images/kayak-chromium-cypress.tar.gz
          docker save kayak/chromium:playwright | gzip > /tmp/docker-images/kayak-chromium-playwright.tar.gz
          docker save kayak/display:latest | gzip > /tmp/docker-images/kayak-display.tar.gz
          docker save kayak/ffmpeg:latest | gzip > /tmp/docker-images/kayak-ffmpeg.tar.gz

      - name: "Upload Docker images to storage"
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            /tmp/docker-images/kayak-*.tar.gz
