name: Docker

env:
  FONTCONFIG_VERSION: 2.14.0
  GNUTLS_VERSION: 3.7.1
  LIBFONTENC_VERSION: 1.1.4
  LIBTASN1_VERSION: 4.17.0
  LIBXFONT2_VERSION: 2.0.4
  LIBXRANDR_VERSION: 1.5.3
  LIBXSHMFENCE_VERSION: 1.3
  NOVNC_VERSION: 1.3.0
  OPENBOX_VERSION: 3.6.1
  PANGO_VERSION: 1.49.3
  TIGERVNC_VERSION: 1.12.0
  XKB_VERSION: 2.32
  XKBCOMP_VERSION: 1.4.5
  XSERVER_VERSION: 1.20.13
  USER_ID: 1000
  GROUP_ID: 1000
  USER_NAME: kayak
  GROUP_NAME: kayak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      fail-fast: true
      matrix:
        platforms: [linux/amd64, linux/arm64/v8]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build "kayak/upx:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/upx:latest
          file: ./docker/upx/Dockerfile
          context: ./docker/upx

      - name: Build "kayak/fontconfig:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/fontconfig:latest
          file: ./docker/fontconfig/Dockerfile
          context: ./docker/fontconfig
          build-args: |
            FONTCONFIG_VERSION=${{ env.FONTCONFIG_VERSION }}

      - name: Build "kayak/crdetector:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/crdetector:latest
          file: ./docker/crdetector/Dockerfile
          context: ./docker/crdetector
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest

      - name: Build "kayak/xset:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/xset:latest
          file: ./docker/xset/Dockerfile
          context: ./docker/xset
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest

      - name: Build "kayak/novnc:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/novnc:latest
          file: ./docker/novnc/Dockerfile
          context: ./docker/novnc
          build-args: |
            NOVNC_VERSION=${{ env.NOVNC_VERSION }}

      - name: Build "kayak/openbox:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/openbox:latest
          file: ./docker/openbox/Dockerfile
          context: ./docker/openbox
          build-args: |
            FONTCONFIG_IMAGE=localhost:5000/kayak/fontconfig:latest
            UPX_IMAGE=localhost:5000/kayak/upx:latest
            LIBXRANDR_VERSION=${{ env.LIBXRANDR_VERSION }}
            OPENBOX_VERSION=${{ env.OPENBOX_VERSION }}
            PANGO_VERSION=${{ env.PANGO_VERSION }}

      - name: Build "kayak/tigervnc:latest"
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          tags: localhost:5000/kayak/tigervnc:latest
          file: ./docker/tigervnc/Dockerfile
          context: ./docker/tigervnc
          build-args: |
            UPX_IMAGE=localhost:5000/kayak/upx:latest
            GNUTLS_VERSION=${{ env.GNUTLS_VERSION }}
            LIBFONTENC_VERSION=${{ env.LIBFONTENC_VERSION }}
            LIBTASN1_VERSION=${{ env.LIBTASN1_VERSION }}
            LIBXFONT2_VERSION=${{ env.LIBXFONT2_VERSION }}
            LIBXSHMFENCE_VERSION=${{ env.LIBXSHMFENCE_VERSION }}
            TIGERVNC_VERSION=${{ env.TIGERVNC_VERSION }}
            XKB_VERSION=${{ env.XKB_VERSION }}
            XKBCOMP_VERSION=${{ env.XKBCOMP_VERSION }}
            XSERVER_VERSION=${{ env.XSERVER_VERSION }}
