name: Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup pnpm
        id: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Set auto-install-peers=true
        run: |
          pnpm config set auto-install-peers true

      - name: Get pnpm store direcroty
        id: pnpm-store
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Lint docs
        working-directory: ./docs
        run: |
          pnpm run lint

      - name: Build docs
        working-directory: ./docs
        run: |
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
