name: "Lint"

on:
  workflow_call:
    inputs:
      pnpm-version:
        description: "pnpm version"
        required: true
        type: number
      paths:
        description: "Paths to run linters on"
        required: true
        type: string

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18, 19 ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup pnpm"
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: "Download workspace from storage"
        uses: actions/download-artifact@v3
        with:
          name: workspace-${{ matrix.node-version }}
          path: /tmp

      - name: "Decompress workspace files"
        run: |
          tar -xzf /tmp/workspace.tar.gz -C . --overwrite

      - name: "Run linters"
        uses: ./.github/actions/execute-for-paths
        with:
          paths: ${{ inputs.paths }}
          run: |
            pnpm lint
