name: Build Docker Images

on:
  workflow_call:
    inputs:
      file:
        description: 'Dockerfile to build'
        required: true
        type: string
      tag:
        description: 'Docker image tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platforms: [linux/amd64, linux/arm64/v8]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: false
          platforms: ${{ matrix.platforms }}
          tags: ${{ inputs.tag }}
          file: ${{ inputs.file }}
