name: "Integration testing"

on:
  workflow_call:
    inputs:
      pnpm-version:
        description: "pnpm version"
        required: true
        type: number

jobs:
  test:
    name: "Integration testing"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18, 19 ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup pnpm"
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: "Download workspace from storage"
        uses: actions/download-artifact@v3
        with:
          name: workspace-${{ matrix.node-version }}
          path: /tmp

      - name: "Decompress workspace files"
        run: |
          tar -xzf /tmp/workspace.tar.gz -C . --overwrite

      - name: "Setup Docker"
        uses: ./.github/actions/setup-docker
        with:
          platforms: arm,arm64,ppc64le,mips64,s390x

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pull Docker images"
        run: |
          docker pull ghcr.io/${{ github.repository }}/anvil:${{ github.ref_name }}
          docker pull ghcr.io/${{ github.repository }}/chromium/${{ github.ref_name }}-cypress
          docker pull ghcr.io/${{ github.repository }}/chromium/${{ github.ref_name }}-playwright
          docker pull ghcr.io/${{ github.repository }}/display:${{ github.ref_name }}
          docker pull ghcr.io/${{ github.repository }}/ffmpeg:${{ github.ref_name }}

#      - name: "Run tests"
#        working-directory: ./examples/playwright
#        run: |
#          mv .env.kayak .env
#          pnpm test
